// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH1cVKO-6WYMVY7MNhQUgPPfXO6TYqmCU',
    appId: '1:383709113689:web:8b6f1d22b111246d47f048',
    messagingSenderId: '383709113689',
    projectId: 'lovefortune-d6ca9',
    authDomain: 'lovefortune-d6ca9.firebaseapp.com',
    storageBucket: 'lovefortune-d6ca9.firebasestorage.app',
    measurementId: 'G-SDZPPGKW33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMlvGcrFkL68ZRhLQ9MOYiY8dxUqONqM',
    appId: '1:383709113689:android:8b12b1f0d7bdab9547f048',
    messagingSenderId: '383709113689',
    projectId: 'lovefortune-d6ca9',
    storageBucket: 'lovefortune-d6ca9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzGlTtOr27GnYed7qrsBMz9GfFes2uGk',
    appId: '1:383709113689:ios:74aade5626fd867b47f048',
    messagingSenderId: '383709113689',
    projectId: 'lovefortune-d6ca9',
    storageBucket: 'lovefortune-d6ca9.firebasestorage.app',
    iosClientId: '383709113689-35e487sjau5m842g54s3539oubeuee1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.lovefortuneApp',
  );
}
